plugins {
    id 'idea'
    id 'fabric-loom' version '+'
}

version = '1.0.8'
group = 'ru.marduk'
archivesBaseName = 'Nedologin-1.19.2'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

configurations {
    compileOnly.extendsFrom(jarJar)
}

dependencies {
    minecraft "com.mojang:minecraft:1.19.2"

    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.2:2023.10.08@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:0.16.9"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.77.0+1.19.2"
    modImplementation include ("maven.modrinth:midnightlib:${project.midnightlib_version}")

    implementation include ('at.favre.lib:bytes:[1.0,1.6)')
    implementation include ('at.favre.lib:bcrypt:[0.4,0.5)')
    implementation include ('org.xerial:sqlite-jdbc:+')
}

allprojects {
    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }

        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }

        maven {
            url = "https://api.modrinth.com/maven"
        }

        mavenCentral()
        gradlePluginPortal()
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        expand 'version': project.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'fabric.mod.json'
    }
}

tasks.jar.mustRunAfter(processResources)

jar {
    manifest {
        attributes([
                "Specification-Title"     : "Nedologin",
                "Specification-Vendor"    : "marduk",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

loom {
    accessWidenerPath = file("src/main/resources/nedologin.accesswidener")
}